---
- name: Add HA Proxy PPA
  ansible.builtin.apt_repository:
    repo: 'ppa:vbernat/haproxy-3.1'

- name: Install HA Proxy
  ansible.builtin.apt:
    name: haproxy
    update_cache: true

- name: Copy HAProxy config
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  register: haproxy_config

- name: Restart HAProxy service
  ansible.builtin.systemd_service:
    state: restarted
    name: haproxy
  when: haproxy_config.changed
