---
aws-efs-csi-driver:
  image:
    repository: public.ecr.aws/efs-csi-driver/amazon/aws-efs-csi-driver
  controller:
    serviceAccount:
      create: true
      name: efs-csi-controller-sa

metrics-server:
  args:
    - --kubelet-insecure-tls
