---
- name: Deploy K8s Cluster
  hosts: localhost
  gather_facts: false
  roles:
    - create_ec2_instances

- name: Provision common components
  hosts: Cluster_k8s_cluster_node
  gather_facts: true
  become: true
  roles:
    - install_common_components

- name: Configure Control Plane node
  hosts: Role_control_plane
  gather_facts: true
  become: true
  roles:
    - configure_control_plane

- name: Configure Worker Nodes
  hosts: Role_worker
  gather_facts: true
  become: true
  roles:
    - configure_worker_nodes

- name: Configure HAProxy
  hosts: Role_haproxy
  gather_facts: true
  become: true
  roles:
    - configure_haproxy

- name: Install Networking Components
  hosts: Role_control_plane
  gather_facts: true
  become: true
  roles:
    - install_k8s_network_solution

- name: Install ArgoCD
  hosts: Role_control_plane
  gather_facts: false
  become: true
  roles:
    - install_argocd
