---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: aws-telephone-sqs-rw
spec:
  mount: aws
  path: creds/telephone-sqs-rw
  rolloutRestartTargets:
    - kind: Deployment
      name: producer-back-deployment
    - kind: Deployment
      name: consumer-back-deployment
  destination:
    name: aws-telephone-sqs-rw
    create: true
    transformation:
      excludes:
        - .*
      templates:
        credentials:
          text: |
            {{ `[default]
            {{ printf "aws_access_key_id = %s \n" (get .Secrets "access_key") }}
            {{ printf "aws_secret_access_key = %s \n" (get .Secrets "secret_key") }}
            {{ printf "aws_session_token = %s \n" (get .Secrets "session_token") }}` }}
  refreshAfter: 30s
  vaultAuthRef: vault-auth-telephone
