---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: aws-telephone-sqs-rw
spec:
  type: aws
  mount: aws
  path: creds/telephone-sqs-rw
  destination:
    name: aws-telephone-sqs-rw
    create: true
  refreshAfter: 30s
  vaultAuthRef: vault-auth-telephone
