---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: aws-telephone-sqs-rw
spec:
  type: aws
  mount: aws
  path: creds/telephone-sqs-rw
  destination:
    name: aws-telephone-sqs-rw
    create: true
    transformation:
      excludes: .*
      templates:
        credentials:
          text: |
            [default]
            {{`- printf "aws_access_key_id=%s" (get .Secrets "access_key") `}}
            {{`- printf "aws_secret_access_key=%s" (get .Secrets "secret_key") `}}
            {{`- printf "aws_session_token=%s" (get .Secrets "session_token") `}}
    path: credentials
  refreshAfter: 30s
  vaultAuthRef: vault-auth-telephone
