---
- name: Init Kubeadm
  ansible.builtin.command:
    cmd: "kubeadm init --pod-network-cidr={{ pod_network_cidr | quote }}"
    creates: /etc/kubernetes/manifests/kube-apiserver.yaml

- name: Create Kube Config folder
  ansible.builtin.file:
    path: /root/.kube
    state: directory

- name: Copy Kube Config in the default folder
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: true

- name: Set Kubectl Autocomplete and Alias
  ansible.builtin.lineinfile:
    path: /root/.bashrc
    regexp: '^{{ item }}'
    line: "{{ item }}"
  loop:
    - "source <(kubectl completion bash)"
    - "alias k=kubectl"
    - "complete -o default -F __start_kubectl k"

- name: Generate join node command
  ansible.builtin.command:
    cmd: kubeadm token create --print-join-command --ttl 5m
  register: kubeadm_join_command

- name: Add join node command to Dummy host
  ansible.builtin.add_host:
    name: "k8s_token_holder"
    join_command: "{{ kubeadm_join_command.stdout }}"

- name: Install Python Kubernetes module
  ansible.builtin.apt:
    name: python3-kubernetes
