---
traefik:
  ports:
    web:
      nodePort: 30080
    websecure:
      nodePort: 30443
  service:
    type: NodePort
  certificatesResolvers:
    leresolver:
      acme:
        email: acme@grr.la
        storage: /ssl-certs/acme.json
        httpChallenge:
          entryPoint: web
  persistence:
    enabled: true
    name: ssl-certs
    path: /ssl-certs
    existingClaim: traefik-acme-certs-efs-pvc
