---
traefik:
  ports:
    web:
      nodePort: 30080
    websecure:
      nodePort: 30443
  service:
    type: NodePort
  certificatesResolvers:
    leresolver:
      acme:
        email: acme@grr.la
        storage: /ssl-certs/acme.json
        httpChallenge:
          entryPoint: web
  persistence:
    enabled: true
    name: ssl-certs
    path: /ssl-certs
    existingClaim: traefik-acme-certs-efs-pvc
  deployment:
    initContainers:
    - name: volume-permissions
      image: busybox:1.36
      command:
        - "sh"
        - "-c"
        - "touch /ssl-certs/acme.json && chmod 600 /ssl-certs/acme.json && chown 65532:65532 /ssl-certs/acme.json"
      volumeMounts:
      - name: ssl-certs
        mountPath: /ssl-certs
