---
traefik:
  ports:
    web:
      nodePort: 30080
    websecure:
      nodePort: 30443
  service:
    type: NodePort
  certificatesResolvers:
    leresolver:
      acme:
        email: my@example.com
        storage: acme.json
        httpChallenge:
          entryPoint: web
