---
traefik:
  ports:
    web:
      nodePort: 30080
    websecure:
      nodePort: 30443
  service:
    type: NodePort
  certificatesResolvers:
    leresolver:
      acme:
        email: acme@grr.la
        storage: /data/acme.json
        httpChallenge:
          entryPoint: web
