---
- name: Create ArgoCD Namespace
  kubernetes.core.k8s:
    name: argocd
    api_version: v1
    kind: Namespace

- name: Install ArgoCD Non-HA
  kubernetes.core.k8s:
    src: "https://raw.githubusercontent.com/argoproj/argo-cd/v{{ argocd_version }}/manifests/install.yaml"
    namespace: argocd
