---
- name: Add ArgoCD Helm Repo
  kubernetes.core.helm_repository:
    name: argocd
    repo_url: "https://argoproj.github.io/argo-helm"

- name: Install ArgoCD Helm Chart
  kubernetes.core.helm:
    name: argocd
    chart_ref: argocd/argo-cd
    update_repo_cache: true
    release_namespace: argocd
    create_namespace: true
    wait: true
    atomic: true
    values:
      configs:
        params:
          server.insecure: true
          server.rootpath: /argocd

- name: Install Traefik Application
  kubernetes.core.k8s:
    definition:
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: ingress-controller
        namespace: "{{ argocd_namespace }}"
      spec:
        project: default
        destination:
          server: https://kubernetes.default.svc
          namespace: "{{ traefik_namespace }}"
        sources:
          - repoURL: "https://traefik.github.io/charts"
            chart: traefik
            targetRevision: "{{ traefik_helm_version }}"
            helm:
              valueFiles:
                - $values/argo-apps/ingress-controller/values.yml
          - repoURL: "https://github.com/ZaiusDR/k8s_playground.git"
            targetRevision: HEAD
            ref: values
        syncPolicy:
          automated:
            selfHeal: true
          syncOptions:
            - CreateNamespace=true
            - ApplyOutOfSyncOnly=true

- name: Setup ArgoCD Ingress
  kubernetes.core.k8s:
    definition:
      apiVersion: traefik.io/v1alpha1
      kind: IngressRoute
      metadata:
        name: argocd-server
        namespace: argocd
      spec:
        entryPoints:
          - web
        routes:
          - kind: Rule
            match: PathPrefix(`/argocd`)
            priority: 10
            services:
              - name: argocd-server
                port: 80
