---
apiVersion: v2
name: newrelic-k8s-integration
description: Helm Chart to Setup NewRelic K8s Integration
version: 0.1.0
appVersion: 1.0.0
dependencies:
- name: nri-bundle
  version: "5.0.110"
  repository: "https://newrelic.github.io/helm-charts"
- name: nr-k8s-otel-collector
  version: "0.8.2"
  repository: "https://newrelic.github.io/helm-charts"
