---
namespace: newrelic
nri-bundle:
  global:
    cluster: K8s_Playground
    lowDataMode: true
    customSecretName: new-relic-license-key
  newrelic-infrastructure:
    privileged: true
  kube-state-metrics:
    image:
      tag: v2.13.0
    enabled: true
  newrelic-prometheus-agent:
    enabled: true
    lowDataMode: true
    config:
      kubernetes:
        integrations_filter:
          enabled: false
  k8s-agents-operator:
    enabled: true
  newrelic-logging:
    enabled: true
  logging:
    enabled: true
    lowDataMode: true
    endpoint: https://log-api.eu.newrelic.com/log/v1
