---
namespace: newrelic
nri-bundle:
  global:
    cluster: K8s_Playground
    lowDataMode: true
    customSecretName: new-relic-license-key
    customSecretLicenseKey: licenseKey
  newrelic-infrastructure:
    privileged: true
  nri-kube-events:
    enabled: true
  kube-state-metrics:
    enabled: true
  newrelic-prometheus-agent:
    enabled: true
  k8s-agents-operator:
    enabled: true
  newrelic-logging:
    enabled: true
    endpoint: https://log-api.eu.newrelic.com/log/v1
    lowDataMode: true
