---
- name: Get Latest Ubuntu 24.04 LTS AMI Id
  set_fact:
    ubuntu_ami_id: "{{ lookup('amazon.aws.aws_ssm', ubuntu_ami_ssm_parameter_path) }}"

- name: Create SSH Access Security Group
  amazon.aws.ec2_security_group:
    name: "ssh-access-sg"
    description: "Security group for accessing by SSH"
    vpc_id: "{{ vpc_id }}"
    rules:
      - proto: tcp
        from_port: "22"
        to_port: "22"
        cidr_ip: "0.0.0.0/0"
  register: ssh_sg

- name: Create Control Plane Security Group
  amazon.aws.ec2_security_group:
    name: "control-plane-sg"
    description: "Security group for Control Plane Node"
    vpc_id: "{{ vpc_id }}"
    rules:
      - proto: tcp
        ports: "{{ control_plane_ports_tcp }}"
        cidr_ip: "{{ vpc_cidr }}"
      - proto: udp
        ports: "{{ udp_ports }}"
        cidr_ip: "{{ vpc_cidr }}"
  register: control_plane_sg

- name: Create Nodes Security Group
  amazon.aws.ec2_security_group:
    name: "nodes-sg"
    description: "Security group for Nodes"
    vpc_id: "{{ vpc_id }}"
    rules:
      - proto: tcp
        ports: "{{ worker_ports_tcp }}"
        cidr_ip: "{{ vpc_cidr }}"
      - proto: udp
        ports: "{{ udp_ports }}"
        cidr_ip: "{{ vpc_cidr }}"
  register: nodes_sg

- name: Create Control-plane Instance
  amazon.aws.ec2_instance:
    key_name: "{{ key_pair_name }}"
    instance_type: "{{ instance_type }}"
    image_id: "{{ ubuntu_ami_id }}"
    security_groups:
      - "{{ ssh_sg.group_id }}"
      - "{{ control_plane_sg.group_id }}"
    wait: yes
    state: started
    exact_count: 1
    tags:
      Name: "control-plane01"
      Cluster: "k8s-cluster-node"
      Role: "control-plane"
    filters:
      tag:Name: "control-plane01"
      instance-state-name: "running"

- name: Create Node Instances
  amazon.aws.ec2_instance:
    key_name: "{{ key_pair_name }}"
    instance_type: "{{ instance_type }}"
    image_id: "{{ ubuntu_ami_id }}"
    security_groups:
      - "{{ ssh_sg.group_id }}"
      - "{{ nodes_sg.group_id }}"
    wait: yes
    state: started
    exact_count: 1
    tags:
      Name: "node0{{ item }}"
      Cluster: "k8s-cluster-node"
      Role: "worker"
    filters:
      tag:Name: "node0{{ item }}"
      instance-state-name: "running"
  loop: "{{ range(1, 3) | list }}"

- name: Refresh Dynamic Inventory
  ansible.builtin.meta: refresh_inventory
