---
- name: Get Latest Ubuntu 24.04 LTS AMI Id
  set_fact:
    ubuntu_ami_id: "{{ lookup('amazon.aws.aws_ssm', ubuntu_ami_ssm_parameter_path) }}"

- name: Create Instances Key Pair
  amazon.aws.ec2_key:
    name: "{{ key_pair_name }}"
  no_log: true
  register: k8s_cluster_key_pair

- name: Create Control-plane Instance
  amazon.aws.ec2_instance:
    key_name: "{{ key_pair_name }}"
    instance_type: t3.micro
    image_id: "{{ ubuntu_ami_id }}"
    wait: yes
    exact_count: 1
    tags:
      Name: "control-plane01"
      Cluster: "k8s-cluster-node"
    filters:
      tag:Name: "control-plane01"
      instance-state-name: "running"

- name: Create Worker Nodes Instances
  amazon.aws.ec2_instance:
    key_name: "{{ key_pair_name }}"
    instance_type: t3.micro
    image_id: "{{ ubuntu_ami_id }}"
    wait: yes
    exact_count: 1
    tags:
      Name: "node0{{ item }}"
      Cluster: "k8s-cluster-node"
    filters:
      tag:Name: "node0{{ item }}"
      instance-state-name: "running"
  loop: "{{ range(1, 3) | list }}"
