---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: new-relic-license-key-vault-secret
  namespace: {{ .Values.namespace }}
spec:
  type: kv-v2
  mount: kvv2
  path: newrelic/k8s
  destination:
    name: new-relic-license-key
    create: true
  refreshAfter: 30s
  vaultAuthRef: vault-auth-newrelic
