---
name: Telephone Services Build
on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        role: [ "producer", "consumer" ]
        tier: [ "front", "back" ]

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ matrix.role }}-${{ matrix.tier }}

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v6
      with:
        context: ./services/telephone/${{ matrix.role }}-${{ matrix.tier }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args:
          api_url="https://producer-back.esuarez.info,ws_url="https://consumer-back.esuarez.info"

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v2
      with:
        subject-name: ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ matrix.role }}-${{ matrix.tier }}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true
