---
argo-cd:
  global:
    podLabels:
      app.newrelic.io/name: argocd
  controller:
    metrics:
      enabled: true
  configs:
    params:
      server.insecure: true
namespace: argocd
install:
  ingressRoute: true
  appOfApps: true
