---
argo-cd:
  global:
    podLabels:
      app.newrelic.io/name: argocd
    podAnnotations:
      newrelic.io/scrape: true
  controller:
    metrics:
      enabled: true
  server:
    metrics:
      enabled: true
  repoServer:
    metrics:
      enabled: true
  dex:
    metrics:
      enabled: true
  configs:
    params:
      server.insecure: true
namespace: argocd
install:
  ingressRoute: true
  appOfApps: true
